### PR TITLE
Change working directory before running robot program.

### PR DESCRIPTION
**Pull request by computer-whisperer**
Do you think this is a good idea?

### CODE REVIEW

**Comment by virtuald** [comment]
I'm willing to entertain it. But, why does it matter? The py directory will be erased on next deploy, so you can't store settings there.

**Comment by computer-whisperer** [comment]
This is primarily for when you try to reference non-python files that also get deployed. A couple of possibilities would be static resources for a web server, or config files that get deployed along with the rest of the code.

**Comment by virtuald** [comment]
Then... do abspath(dirname(__file__)) ?

**Comment by computer-whisperer** [comment]
The issue I am running into atm is that if your Robot class is not in robot.py, but imported from a library file, there is no good way to obtain the path of robot.py. I suppose you could do some sort of a ```library.set_root_dir(abspath(dirname(__file__)))``` -- but I thought it might be easier there, and of no issue here, just to use the current directory.

If you don't think it fits here, that's fine.

**Comment by virtuald** [comment]
In general, you have no guarantee that your code is being ran from any particular directory, so it's dangerous to rely on the current directory if you didn't set it. 

I don't see anything wrong with this, but in general when I write scripts that depend on resources, I try to do them relative to where my code is running or at absolute paths as those are constants I can guarantee, unless its a tool like `git` that works based on the current location.

**Comment by virtuald** [comment]
I am reverting the effects of this commit, as the robot deployment does not seem to actually work when you do this.

**Pull request merged**
