### PR TITLE
Added a check for the correct robot.py capitalization. 

### PR DESCRIPTION
**Pull request by benjiboy50fonz**
In response to #186, I propose a solution.

Because `os.listdir` offers a list of directory contents, and we have a specific file we want to search for, I simply added a check to see if `robot.py` was in the directory which called the deploy command. If it's not, it assumes incorrect capitalization and fails.

I did it this way as well to prevent programmers from intentionally naming their file "Robot.py", and then encountering issues down the road. Hopefully this cuts them short, and gives them enough clarity that they can modify their codebase to meet this naming standard.

Criticism is very welcome!

### CODE REVIEW

**Comment by benjiboy50fonz** [comment]
I was very behind on my commits it seems; how unfortunate.

**Comment by auscompgeek** [comment]
I'm pretty sure we already have a check for robot.py that's overridable. We need to improve that check, not break that entirely.

**Comment by benjiboy50fonz** [comment]
The check is still present.

**Comment by auscompgeek** [comment]
Sure, but what I'm saying is that this check and that check seem to be completely different. That breaks the intent of the override, I think.

**Comment by virtuald** [comment]
@benjiboy50fonz have you actually tested this PR? As @auscompgeek I don't think this is doing what you intended.

**Comment by benjiboy50fonz** [comment]
Ok, I understand @auscompgeek . @virtuald, I haven't had access to my RIO yet, but I will soon. I'd set up a VM, but I'm on Windows and WSL is a pain, as well as a VM in a VM.

**Comment by virtuald** [comment]
It's generally a bad idea to make changes to code without testing those changes.

**Comment by virtuald** [comment]
... so what's going on with this?

**Comment by virtuald** [comment]
This is a fine idea, but it needs to actually work if we're going to accept it.

**Pull request closed without merging**
