### PR TITLE
Add Github Action to bump requirements

### PR DESCRIPTION
**Pull request by TheTripleV**
## Functionality:
When this repo receives a webhook with a package name and repo name:

1. Get the latest tag at the repo
2. Check tag against current version in `requirements.txt`
3. Update requirements.txt
4. Commit, Push, Tag, Push

## Notes:

- This action uses a repo access token for git instead of `secrets.GITHUB_TOKEN`. A push made using GITHUB_TOKEN will not trigger other actions whereas using another private access token will.

### CODE REVIEW

**Comment by virtuald** [comment]
Uses this? https://github.com/marketplace/actions/repository-dispatch

**Comment by TheTripleV** [comment]
No. On the other end, I've been using a POST
```
        curl -X POST https://api.github.com/repos/robotpy/pyfrc/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u TheTripleV:${{ secrets.PYFRC_ACCESS_TOKEN }} \
            --data '{"event_type": "tag", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "package_name": "wpilib"}}'
```
but i guess that would work too. I'll try it out. That shouldn't affect this side of the script though.

**Comment by TheTripleV** [comment]
repository-dispatch isn't working for me:
My yaml
```
    - name: Ping pyfrc
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PYFRC_ACCESS_TOKEN }}
        repository: TheTripleV/pyfrc
        event-type: tag
        client-payload: '{"repository": "'"$GITHUB_REPOSITORY"'", "package_name": "wpilib"}}'
```

Github Actions is throwing a yaml syntax error on the `event-type` line.

**Comment by TheTripleV** [comment]
Yes, now it does use https://github.com/marketplace/actions/repository-dispatch on the sending side.

**Comment by virtuald** [comment]
Hm, can't the sending repo send this the tag? Then it doesn't need to check the repo out.

**Comment by virtuald** [comment]
Thanks!

**Comment by virtuald** [comment]
I've added a REPO_ACCESS_TOKEN secret to the relevant repos.

**Pull request merged**
